### ISSUE TITLE
uninitialized constant RSpec::Mocks::ArgumentListMatcher

### ISSUE THREAD

**Issue by martenlienen** [technicalpickles/rspec-spies#12]
Hi,
when I use the newest version of your gem in a rails environment using RSpec, I get the following error: uninitialized constant RSpec::Mocks::ArgumentListMatcher.

This error is thrown from lib/rspec-spies.rb:22 and it can be fixed by putting "require 'rspec/mocks/argument_list_matcher'" in line 20.

Regards,
CQQL

**Comment by gylaz** [comment]
I'm seeing this too on version 2.1.2. It wasn't happening before.

**Comment by jamesarosen** [comment]
Released version 2.1.3 with a fix for this.
